local: &local
  adapter: mysql
  host: localhost
  encoding: utf8
  username: root
  password: 

development:
  database: portablelight_development
  <<: *local

test:
  database: portablelight_test
  <<: *local

staging:
  database: portablelight_staging
  <<: *local

production:
  adapter: mysql
  encoding: utf8
  host: localhost
  database: portablelight_production
  username: portablelight
  password: f83tig74JUjFeL9K

