--- 
- :name: acts_as_markup
  :version: = 1.3.3
- :name: paperclip
  :version: = 2.3.1.1
- :name: authlogic
  :version: = 2.1.3
- :name: cancan
  :version: = 1.0.2
- :name: will_paginate
  :version: = 2.3.12
- :name: inherited_resources
  :version: = 0.9.2
- :name: formtastic
  :version: = 0.9.2
- :name: validation_reflection
  :version: = 0.3.5
- :name: configliere
  :version: = 0.0.5
- :name: rails
  :version: 2.3.5
