:ruby: ree
:application: portablelight
:user: rails
#:time_zone: UTC
:deploy_to: /srv/portablelight
:domain: portablelight.org
:domain_aliases:
 - portablelight.crushserver.com
 - www.portablelight.org
 - portablelightproject.org
 - www.portablelightproject.org
#:scm: git
:repository: git@github.com:crushlovely/portablelight.git
# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
#:app_symlinks:
#  - uploads
#
# Use :local_config to copy directories straight from your local project directory
# to the server: these are files that you don't have/want in scm.
:shared_config:
 - config/database.yml
#
# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config
# After specifying a gem with config.gem, run 'rake moonshine:gems'
# to update config/gems.yml. If the gem depends on native packages,
# tell Moonshine here:
# :apt_gems:
#  thoughtbot-paperclip:
#    - imagemagick
#    - libmagick9-dev
# See all the options for Passenger, Apache vhosts, and MySQL in the
# respective templates: moonshine/lib/moonshine/manifest/rails/templates
:passenger:
  :max_pool_size: 2
  :version: 2.2.4
:mysql:
  :innodb_buffer_pool_size: 64M
